# ____
# PRODUCTS
# ____


# collections: 
  # - name: pages
      # files: 
          #<start snippet>
          - name: "products"
            label: "Products" 
            folder: "content/products"
            create: true
            fields:
              - name: "title"
                label: "Title"
                widget: "string"

              - name: "description" 
                label: "Short Description"
                widget: "string"
            
              - name: "image"
                label: "feature image"
                widget: "image"
                choose_url: true
                i18n: "duplicate"
                media_library:
                  config:
                    multiple: false
              - name: "content" 
                label: "Content"
                widget: "markdown"
              - *seo
            #<end snippet>

# ___
# Dynamic Fields:
# ___


## Sub-Anchors
images: &dfImages
  name: "images"
  label: "Images"
  widget: "image"
  choose_url: true
  media_library: 
    config:
      multiple: true

dfImage: &dfImage
  label: "Dynamic Field - Single image"
  name: "image"
  widget: "image"
  choose_url: true
  media_library:
    config:
      multiple: false

dfVideo: &dfVideo
  label: "Dynamic Field - Video"
  name: "video"
  widget: "file"
  choose_url: true
  media_library:
    config:
      multiple: false

dfAudio: &dfAudio
  label: "Dynamic Field - Audio"
  name: "audio"
  widget: "file"
  media_library:
    config: 
      multiple: false

dfText: &dfText
  name: "dfText"
  label: "Dynamic Field - Text"
  widget: "markdown"

dfSettings: &dfSettings
  name: "dfSettings"
  label: "Settings (required)"
  widget: "object"
  hint: "sets styling rules per section"
  required: true
  fields:
    - name: "size"
      label: "Size"
      widget: "select"
      options: ["small", "large"]
    - name: "background"
      label: "Background"
      widget: "select"
      options: ["dark", "light"]

## Main-anchor (called in collections/page/dynamicFields)
dynamicFields: &dynamicFields
  name: "dynamicField"
  label: "Dynamic Field"
  widget: "list"
  hint: "pick the desired field type(s)"
  required: true

  types: 
    - name: "text"
      label: "Field: Text Editor"
      widget: "object" 
      collapsed: true
      fields:
        - *dfText
    - name: "image"
      label: "Field: Single Image"
      widget: "object"
      collapsed: true  
      fields:
        - *dfImage
    - name: "images"
      label: "Field: Multiple images"
      widget: "object"
      collapsed: true
 
      fields: 
        - *dfImages
        - name: "displayType"
          label: "select display type"
          widget: "select"
          options: ["carousel", "lightbox"]
          required: true

    - name: "video"
      label: "Field: Video"
      widget: "object"
      collapsed: true  
      fields:
        - *dfVideo
        - name: "autoplay"
          label: "autoplay"
          widget: "boolean"
        - name: "muted"
          label: "muted"
          widget: "boolean"
        - name: "loop"
          label: "loop"
          widget: "boolean"
          
    - name: "audio"
      label: "Field: Audio"
      widget: "object"
      collapsed: true  
      fields:
        - *dfAudio


# collections: 
  # - name: pages
      # files: 
          #<start snippet>
          - name: "dynamicFields"
            label: "Dynamic Field"
            file: "content/pages/dynamic-fields.md"
            format: "frontmatter"
            fields:
              - { name: "title", label: "Title", widget: "string", i18n: true}
              - name: "sections"
                label: "Sections"
                widget: "list"
                hint: "every section can have on or more Dynamic Fields"
                label_singular: "section"
                fields: 
                  - { name: "name", label: "Section Name", widget: "string"}
                  - *dynamicFields
                  - *dfSettings
              - *seo
          #<end snippet>